# Generated by Django 4.0.4 on 2022-08-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=50, verbose_name='Название теста')),
                ('categoriy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_user.categoriy')),
            ],
            options={
                'verbose_name': 'Название теста',
                'verbose_name_plural': 'название тестов',
            },
        ),
    ]
